In [2]:
import pandas as pd
print(pd.__version__)

2.3.3

In [3]:
import pandas as pd
dataset=pd.read_csv(r'C:\Users\oshan\Desktop\weather.csv')

In [5]:
dataset

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [21]:
dataset.shape

(366, 22)

In [23]:
del dataset['WindGustDir']

In [24]:
dataset

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,30.0,SW,NW,6.0,20,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,39.0,E,W,4.0,17,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,85.0,N,NNE,6.0,6,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,54.0,WNW,W,30.0,24,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,50.0,SSE,ESE,20.0,28,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,76.0,SSE,NW,7.0,50,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,48.0,NNW,NNW,2.0,19,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,43.0,ENE,ENE,11.0,9,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,46.0,SSW,WNW,6.0,28,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,78.0,NW,WNW,31.0,35,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [25]:
dataset.drop(columns=['WindDir9am','WindDir3pm'])

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,30.0,6.0,20,68,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,39.0,4.0,17,80,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,85.0,6.0,6,82,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,54.0,30.0,24,62,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,50.0,20.0,28,68,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,76.0,7.0,50,38,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,48.0,2.0,19,45,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,43.0,11.0,9,63,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,46.0,6.0,28,69,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,78.0,31.0,35,43,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [30]:
data=dataset[['MaxTemp','WindGustSpeed','Pressure9am']]

In [31]:
data

     MaxTemp  WindGustSpeed  Pressure9am
0       24.3           30.0       1019.7
1       26.9           39.0       1012.4
2       23.4           85.0       1009.5
3       15.5           54.0       1005.5
4       16.1           50.0       1018.3
..       ...            ...          ...
361     30.7           76.0       1016.1
362     28.4           48.0       1020.0
363     19.9           43.0       1024.0
364     26.9           46.0       1021.0
365     30.2           78.0       1009.6

[366 rows x 3 columns]

In [32]:
data.count()

MaxTemp          366
WindGustSpeed    364
Pressure9am      366
dtype: int64

In [45]:
data.tail(10)

     MaxTemp  WindGustSpeed  Pressure9am
356     15.0           70.0       1023.4
357     18.0           48.0       1026.6
358     20.7           39.0       1023.2
359     25.5           43.0       1018.8
360     26.1           43.0       1017.6
361     30.7           76.0       1016.1
362     28.4           48.0       1020.0
363     19.9           43.0       1024.0
364     26.9           46.0       1021.0
365     30.2           78.0       1009.6

In [34]:
data.head(10)

   MaxTemp  WindGustSpeed  Pressure9am
0     24.3           30.0       1019.7
1     26.9           39.0       1012.4
2     23.4           85.0       1009.5
3     15.5           54.0       1005.5
4     16.1           50.0       1018.3
5     16.9           44.0       1023.8
6     18.2           43.0       1024.6
7     17.0           41.0       1026.2
8     19.5           48.0       1026.1
9     22.8           31.0       1024.1

In [6]:
data =pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
data

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [7]:
data =pd.DataFrame([1,2,3,4,5])
data

   0
0  1
1  2
2  3
3  4
4  5

In [9]:
lst=[[1,2,3,4,5],[1,3,5,7,9]]
df=pd.DataFrame(lst)
df

   0  1  2  3  4
0  1  2  3  4  5
1  1  3  5  7  9

In [11]:
dict={'Name':['Kamal','Saman','Nimal'],'Marks':[80,60,70]}
df=pd.DataFrame(dict)
df

    Name  Marks
0  Kamal     80
1  Saman     60
2  Nimal     70

In [12]:
dict1={'Kamal':[5,4,3,8],'Nimal':[4,4,4,9]}
df1=pd.DataFrame(dict1)
dict2={'Saman':[1,4,1,8],'Sunil':[4,9,9,0]}
df2=pd.DataFrame(dict2)

In [13]:
df1

   Kamal  Nimal
0      5      4
1      4      4
2      3      4
3      8      9

In [14]:
df2

   Saman  Sunil
0      1      4
1      4      9
2      1      9
3      8      0

In [15]:
pd.concat([df1,df2])

   Kamal  Nimal  Saman  Sunil
0    5.0    4.0    NaN    NaN
1    4.0    4.0    NaN    NaN
2    3.0    4.0    NaN    NaN
3    8.0    9.0    NaN    NaN
0    NaN    NaN    1.0    4.0
1    NaN    NaN    4.0    9.0
2    NaN    NaN    1.0    9.0
3    NaN    NaN    8.0    0.0

In [17]:
pd.concat([df1,df2],axis=1)

   Kamal  Nimal  Saman  Sunil
0      5      4      1      4
1      4      4      4      9
2      3      4      1      9
3      8      9      8      0